### ISSUE TITLE
Memory leak of OrderedHash::HashNodes

### ISSUE THREAD

**Issue by SunnyDU1** [cubiclesoft/cross-platform-cpp#1]
OrderedHash::HashNodes doesn't seem to be cleaned up on destruction.

**Comment by cubiclesoft** [comment]
Got an example?  Empty() is called by the destructor, which defaults DeleteNodes to true, which, in turn, calls delete on each node.  As far as I can tell, everything should be cleaned up.

**Comment by SunnyDU1** [comment]
Each node is cleaned up just fine, but HashNodes, your array that stores the pointers to each node, is not.

Empty() resets each position of HashNodes to null with...

   for (x = 0; x < HashSize; x++)  HashNodes[x] = NULL;

...but there's nothing following that that does a delete [] HashNodes.  The only place you're cleaning up HashNodes is ResizeHash.  You need a delete[] HashNodes in the destructor following your empty.

**Comment by cubiclesoft** [comment]
Thanks for catching that leak.  Sorry about the delay.  Been working on another project.
