### ISSUE TITLE
Would you mind adding the licenses into the repo?

### ISSUE THREAD

**Issue by assarbad** [cubiclesoft/cross-platform-cpp#2]
Hi,

saw your link from the WTL mailing list. Would you mind adding the licenses (MIT and LGPL if I understand it correctly) to the repository?

The description is quickly changed, but having this part of the repository and perhaps even the file headers makes it a more steadfast statement that it's these licenses.

Thanks for reading.

**Comment by cubiclesoft** [comment]
A few thoughts:  Legally speaking, what is there now is sufficient to cover all copyright law and other laws related to software licensing.  Both are very well-known licenses.  README.md is part of the repo and is included in change tracking and history in git.  All files are easily modified/changed with git.  I don't see any extra benefit and worrying about this would just add more busy work for me.

The license is actually, "MIT *or* LGPL, your choice".  It's a legally binding statement that says that you, the developer, get to pick which license of those two you want to license the software under.  It's pretty clear legalese from where I sit.

I'd be more apt to listen to license placement quibbles if I were to receive some real help on this project.
