### ISSUE TITLE
Using named mutex in a dynamic library on MacOS

### ISSUE THREAD

**Issue by leochou0729** [cubiclesoft/cross-platform-cpp#6]
Hello,
  I'm trying to use the Sync::Mutex in my dynamic library, which is shared by multiple processes. 
  This is the snippet:

```
static CubicleSoft::Sync::Mutex gSyncMutex;

__attribute__((constructor))
static void initializer(void)
{
    gSyncMutex.Create("/my_mutex");
}

__attribute__((destructor))
static void finalizer(void)
{
}


void access_resourse()
{
    gSyncMutex.Lock();

    //access the resouce

    gSyncMutex.Unlock();
}
```

This doesn't work. Could you please show me how to use your code correctly? Thanks!

**Comment by leochou0729** [comment]
Right now, when calling access_resource(), my application will crash immediately. I don't know if it is process-safe to create Sync::Mutex in entry point in my dynamic library.

**Comment by cubiclesoft** [comment]
The code above doesn't check the return value of `Create()` so there's no way to know if mutex creation was successful or not.

https://github.com/cubiclesoft/cross-platform-cpp/blob/master/test_suite.cpp#L321

Avoid using a '/' in the name.  The library will do that for you on appropriate platforms and a '/' character might cause mutex creation failure.  If you still encounter a crash bug, run the test suite on your platform to verify that it's not some more basic issue with the OS.  Mac OSX doesn't fully support POSIX, which is the primary reason that the *NIX platform locking logic gets pretty hairy.
